# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello/central/user_service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'hello/central/user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n hello/central/user_service.proto\x12\rhello.central\"\x0e\n\x0cHelloRequest\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"4\n\x0eListUsersReply\x12\"\n\x05users\x18\x01 \x03(\x0b\x32\x13.hello.central.User\"!\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"?\n\x0f\x43reateUserReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\xe0\x01\n\x0bUserService\x12?\n\x05Hello\x12\x1b.hello.central.HelloRequest\x1a\x19.hello.central.HelloReply\x12@\n\tListUsers\x12\x14.hello.central.Empty\x1a\x1d.hello.central.ListUsersReply\x12N\n\nCreateUser\x12 .hello.central.CreateUserRequest\x1a\x1e.hello.central.CreateUserReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello.central.user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=51
  _globals['_HELLOREQUEST']._serialized_end=65
  _globals['_HELLOREPLY']._serialized_start=67
  _globals['_HELLOREPLY']._serialized_end=96
  _globals['_EMPTY']._serialized_start=98
  _globals['_EMPTY']._serialized_end=105
  _globals['_USER']._serialized_start=107
  _globals['_USER']._serialized_end=139
  _globals['_LISTUSERSREPLY']._serialized_start=141
  _globals['_LISTUSERSREPLY']._serialized_end=193
  _globals['_CREATEUSERREQUEST']._serialized_start=195
  _globals['_CREATEUSERREQUEST']._serialized_end=228
  _globals['_CREATEUSERREPLY']._serialized_start=230
  _globals['_CREATEUSERREPLY']._serialized_end=293
  _globals['_USERSERVICE']._serialized_start=296
  _globals['_USERSERVICE']._serialized_end=520
# @@protoc_insertion_point(module_scope)
